### ISSUE TITLE
Desktop notifications / Mac dock bounce on errors

### ISSUE THREAD

**Issue by oakmac** [oakmac/cuttle#14]
User should be able to enable and configure desktop notifications and/or Mac dock bounce when a build fails or has a warning.

**Comment by oakmac** [comment]
I think this might be the [flashFrame](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#browserwindowflashframeflag) flag.

**Comment by oakmac** [comment]
Probably this: https://github.com/atom/atom-shell/blob/master/docs/api/app.md

**Comment by oakmac** [comment]
The errors and warnings still need work in order to improve their display - Issue #25 

This issue needs testing on Windows and then it's complete.

**Comment by shaunlebron** [comment]
Created an Atom Shell issue for the notification icon https://github.com/atom/atom-shell/issues/1025

**Comment by shaunlebron** [comment]
overwriting the bundle identifier in the release script, and clearing the notification center cache seems to have worked:
![notify-icon](https://cloud.githubusercontent.com/assets/116838/5796146/f882eec2-9f66-11e4-8af1-e089c498c3bd.png)

**Comment by oakmac** [comment]
Desktop notifications are not working on Windows. Looks like they're not supported in atom-shell: [Issue 262](https://github.com/atom/atom-shell/issues/262).

Other options are: [Growl](http://www.growlforwindows.com/gfw/), [grunt-notify](https://github.com/dylang/grunt-notify), [system tray balloons](https://github.com/atom/atom-shell/blob/master/docs/api/tray.md#traydisplayballoonoptions) (would require implementing Issue #51 ).

**Comment by oakmac** [comment]
Another option: we could ship [Notifu](http://www.paralint.com/projects/notifu/) with the Windows release and use that.

**Comment by oakmac** [comment]
Closing this; made a new issue for Windows Growl notifications (Issue #63).
