### ISSUE TITLE
versioning / updating / about information

### ISSUE THREAD

**Issue by oakmac** [oakmac/cuttle#38]
We need to provide some way for users to see which version of the tool they are running and provide a clear path for when and how the tool should be upgraded.

Maybe it should "call home" in some capacity or check a pre-determined HTTP endpoint with the most recent version?

**Comment by shaunlebron** [comment]
popcorntime calls [this endpoint](http://popcorntime.io/update.json) for checking latest version.  We can create a file like this in our repo and call out to it in the app.

**Comment by shaunlebron** [comment]
we can just update the "app" folder to make for quicker upgrades.

**Comment by oakmac** [comment]
I really like the way that Evernote's Skitch handles updates. When you start the application it tells you that a new version is available and asks you if you want to upgrade. If you click "yes", then it downloads the update, installs it, and restarts. Else it just loads the app like normal.

We should be able to reproduce a similar workflow pretty easily by downloading a new "app" folder and restarting the atom-shell BrowserWindow instance.

**Comment by oakmac** [comment]
We need some variant of this before our v1.0 release.

**Comment by shaunlebron** [comment]
will do this tonight
