### ISSUE TITLE
make release script rebuild from scratch

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cuttle#72]

**Comment by oakmac** [comment]
The release process should ensure that we have a fresh copy of `main.js` from the ClojureScript source files and a fresh `main.css` file from the `.less` files.

**Comment by comamitc** [comment]
Seems like a combination of [grunt clean](https://github.com/gruntjs/grunt-contrib-clean) and `lein clean` should do the trick?

**Comment by shaunlebron** [comment]
`grunt fresh-release`
