### ISSUE TITLE
Cannot install Cuttle to a path with spaces on Windows

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cuttle#73]
Cuttle installed with the Windows installer was broken because of a space in the path to `lein.bat`, "Program Files" being the offender.  Node's child_process.spawn function can't seem to handle a space in the path of the command executable, no matter what I do:

- Escaping the spaces with backslashes didn't work (but it allows spaces in paths on Mac and Linux)
- Quoting the paths didn't work
- [superspawn](https://www.npmjs.com/package/superspawn) didn't work

Looks like a known problem: http://stackoverflow.com/q/21356372/142317

**Comment by shaunlebron** [comment]
For now, the installer just defaults to `C:\Cuttle`

**Comment by oakmac** [comment]
The installer has worked on my Windows machine in the past. Wonder what has
changed...

**Comment by shaunlebron** [comment]
My VM is running Win8.  I don't think I ever tested the installation to
compile a project in the past for some reason.

And the lein-path function hasn't changed in a long time.

**Comment by oakmac** [comment]
Think we're good on this now.
