### ISSUE TITLE
Application fails to complete launch

### ISSUE THREAD

**Issue by NPrescott** [oakmac/cuttle#74]
After a successful installation, the application displays:
```
The ClojureScript compiler requires Java SE Runtime 7+.
Please install, then restart this tool.
```
and any attempt to close the application results in:

![error](https://cloud.githubusercontent.com/assets/4661088/5943667/96e87a92-a6e6-11e4-8c29-52f305ef6b9a.png)

Clicking `OK` redraws the screen to a spinning "Shutting Down" message that never completes. The only means to close the application is to manually kill the process.

 - Windows 7 Enterprise Edition
   - Service Pack 1

```
C:\Users\nopresco>java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

Running the application as administrator has no effect on the problem.

**Comment by oakmac** [comment]
Thanks; I'll look into this.

**Comment by shaunlebron** [comment]
Thanks nolan.  I need to add logging so we can figure out what's going on.

**Comment by oakmac** [comment]
I'm not 100% sure what went wrong here, but the error happens when writing the `window.json` file. Since it's not super important that that operation succeeds, I just wrapped it in a `try`/`catch`.

**Comment by comamitc** [comment]
Does cuttle require the JAVA_HOME variable to be set?  

If no, could having it set on a windows machine cause this issue?

**Comment by oakmac** [comment]
Is this still an issue with v1.1?

**Comment by NPrescott** [comment]
Still an issue with v1.1, with some changes in behavior. On initial startup after a successful install, the following error is thrown:

![cuttle_error](https://cloud.githubusercontent.com/assets/4661088/6004932/2322e356-aacc-11e4-9030-f06bf72e890d.png)

and the contents of `%HOME%/AppData/Roaming/Cuttle` is a single file, `DevToolsExtensions` which contains only `[]`.

Clicking through the error still results in:
```
The ClojureScript compiler requires Java SE Runtime >= 7.
Please install, then restart this tool.
```

However, any further attempts to start the application do not result in the error dialog (only the Java 7 message). A `cuttle.log` file is then available in the `/AppData/Roaming/Cuttle` directory with the following logs:
```
2015-02-02T17:13:10.470Z - info: -------------------------------------------
2015-02-02T17:13:10.473Z - info: Cuttle started
2015-02-02T17:13:10.473Z - info: build version: 1.1
2015-02-02T17:13:10.473Z - info: build date:    2015-01-30
2015-02-02T17:13:10.474Z - info: build commit:  af19436933a8c248488a8710407dd824ccd4bab7
2015-02-02T17:13:10.474Z - info: -------------------------------------------
2015-02-02T17:13:10.495Z - info: atom-shell ready event triggered, starting app
2015-02-02T17:13:10.495Z - info: creating browser window
2015-02-02T17:13:10.956Z - info: sending path to client C:\Users\nopresco\AppData\Roaming\Cuttle
2015-02-02T17:13:10.959Z - info: client: STARTING CLIENT
2015-02-02T17:13:10.959Z - info: client: received app data path: C:\Users\nopresco\AppData\Roaming\Cuttle
2015-02-02T17:13:10.960Z - info: client: using lein at: c:\cuttle-bin\lein.bat with-profile +cuttle 
2015-02-02T17:13:10.961Z - info: client: copying lein.bat to our windows bin dir
2015-02-02T17:13:11.024Z - info: client: checking java version
2015-02-02T17:13:11.188Z - info: client: couldn't run java -version
```
the last line being the most interesting, as I can run:
```
C:\Users\nopresco>java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```
without issue. Let me know if you need more information or I should try something different. 
:+1: on the logging @shaunlebron

**Comment by oakmac** [comment]
Thanks Nolan - this is very helpful

**Comment by oakmac** [comment]
I think this is a permissions problem. We should check whether a user has permission to execute things on the command line at all, then do the Java version check.

**Comment by comamitc** [comment]
You might want to right click and run as administrator; that should show if
it's a permission problem.

**Comment by shaunlebron** [comment]
@NPrescott can you copy this file to "C:\Program Files\Cuttle\app\js\main.js":

https://gist.githubusercontent.com/shaunlebron/3166a9234f926c1ce9bd/raw/main.js

It logs the actual error received when running `java -version`.  So that'll give us more to go on.  Thanks

**Comment by NPrescott** [comment]
```
2015-02-02T19:17:15.578Z - info: client: checking java version
2015-02-02T19:17:15.691Z - info: client: couldn't run java -version: Error: Command failed: C:\Windows\system32\cmd.exe /s /c "java -version"
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
```

So this looks environmental to my machine and not so much an issue with Cuttle itself. When I get a few minutes I'll clear any lingering registry keys and retry.

I'm not clear on how the command is failing, but it should be easy enough to fix on my end.
```
C:\Users\nopresco>C:\Windows\System32\cmd.exe /s /c "java -version"
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

**Comment by comamitc** [comment]
If it's not OK with java 1.8 then the docs should be changed.  They currently say: 

`(Please make sure to install a JRE >= 7)`

Perhaps I'm misunderstanding the error.

**Comment by NPrescott** [comment]
Closing this issue as my system is now working. Windows does not seem to be cleaning up after itself properly after uninstalling things (or I don't understand some of the particulars involved here) - but to get my system working I deleted the following files:

- `C:\Windows\SysWOW64\java.exe`
- `C:\Windows\SysWOW64\javaws.exe`
- `C:\Windows\SysWOW64\javaw.exe`
- `C:\Windows\System32\java.exe`
- `C:\Windows\System32\javaws.exe`
- `C:\Windows\System32\javaw.exe`

Java is still installed and is still responding correctly:
```
C:\Users\nopresco>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.7.0_71

C:\Users\nopresco>java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

In so much as the application needing an issue or updates to the UI/docs regarding `JRE >= 7` - I'll leave that up to @comamitc

**Comment by oakmac** [comment]
Thank you for the report on this. There are a few take-aways for Cuttle IMO

- Whenever Cuttle runs a command and the output is not what we were expecting, we should probably show a useful error with the output of the program in order to help debugging.
- Logging is super-helpful in diagnosing these things.
- People's environments are a mess and I don't think we'll be able to predict all edge cases. We should just program defensively and make as few assumptions as possible about people's machines.
