### ISSUE TITLE
convert scripts to shelljs

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cuttle#87]
Looks like we can get portability with shelljs for all the things I wanted bash for:
https://github.com/arturadib/shelljs

was growing tired of maintaining batch/bash scripts, requiring cygwin/mingw for the release script, and of chris complaining about it.

**Comment by oakmac** [comment]
"chris complaining about it" --> :+1:

**Comment by shaunlebron** [comment]
I'll add more logging in the gruntfile, but @oakmac you should be happy now!

**Comment by oakmac** [comment]
So happy  ;)
