### ISSUE TITLE
ensure directories and files exist; prevent ENOENT error

### ISSUE THREAD

**Issue by oakmac** [oakmac/cuttle#92]
re: Issue #74 

We should use fs-extra's [ensureDir](https://github.com/jprichardson/node-fs-extra#ensuredirdir-callback) on app load to make sure app-data exists as well as any other directories or files we depend on touching.

In other words, Cuttle users should never see an ENOENT error.

**Comment by oakmac** [comment]
![cuttle-error-on-windows](https://cloud.githubusercontent.com/assets/98485/6280432/6b5020e0-b872-11e4-9f35-af71a3c065b6.png)

Saw this error on a fresh install on Windows 7.

**Comment by oakmac** [comment]
Think commit 29e84be should do the trick, but this needs testing.
Paging @NPrescott

**Comment by NPrescott** [comment]
Working for me, no errors in a fresh Windows install.

:+1:

**Comment by oakmac** [comment]
thank you sir!
