### ISSUE TITLE
project.clj error results in frozen UI

### ISSUE THREAD

**Issue by imalooney** [oakmac/cuttle#93]
Play-by-play:
I made a bunch of changes to add a new page and build to my project. I attempted to reload project.clj (First tried just stopping and autocompiling again, but then realized the refresh icon was for project.clj changes.)

Cuttle screen froze on me as below with this console log:

![screen shot 2015-02-06 at 11 22 22 am](https://cloud.githubusercontent.com/assets/4466672/6087894/8d2e8b90-ae16-11e4-802d-f79e0dc14d60.png)

log:
main.js:27626 Uncaught All [:compiler :output-dir] options must be distinct.

I tried to add the project to Cuttle again because that instance seemed screwed. But it still didn't seem to load with updated project.clj (obvy bc there was an error). So i just wanted to shut her down by hitting the X….that froze on "shutting down" for about 4 minutes before I gave up and selected “close Atom” from the menu.

Opened Cuttle up again and old instance was still there frozen as before. I closed the new instance of my project here and closed Cuttle.

Went to project.clj. I did indeed have two builds with the same :output-dir. I made a new :output-dir for one. Re-opened Cuttle. Now everything is just peachy.

I am running v1.1 on Mac OS X 10.9.5.

And I like chocolate ice cream.

**Comment by shaunlebron** [comment]
Thanks @imalooney, I'll take a look at this, after getting some ice cream.

**Comment by shaunlebron** [comment]
Some notes:

- Each build needs a unique `:output-dir` key.
- `cuttle.cljsbuild.config/set-default-output-dirs` throws this error (code ripped from cljsbuild plugin)
- need a strategy for warning malformed project.clj

**Comment by shaunlebron** [comment]
Closing, will track in #96
