### ISSUE TITLE
Build is compiled even when not selected

### ISSUE THREAD

**Issue by pgambling** [oakmac/cuttle#95]
![screen shot 2015-02-09 at 11 51 06 am](https://cloud.githubusercontent.com/assets/688912/6111917/1c50e60a-b052-11e4-8262-0bb7138d24e6.png)

I have two builds, debug and prod. I unselected prod and started auto build on debug. However, debug never compiles and prod always compiles even though it was not selected.

Here is my project.clj -> https://gist.github.com/pgambling/82fe893fda71919a3c1d

**Comment by shaunlebron** [comment]
Thanks will look into it.  (Just FYI, mac lets you [screencap a window](https://github.com/shaunlebron/cljsjs-chance-test) without tracing it manually.)

**Comment by shaunlebron** [comment]
Problem is that the output file is the same for both builds.  We have to determine the build key from the output file when parsing the compiler output:

```
Compiling ClojureScript.
Compiling "public/js/out/gso.js" from ["src-cljs"]...   # <-- is this for debug or prod? idk
Successfully compiled "public/js/out/gso.js" in 30.504 seconds.
```

@pgambling, probably best to rename the output file to gso.min.js for prod build.

@oakmac, thoughts on producing a warning for this in the UI?

**Comment by oakmac** [comment]
I agree the solution here is to create a different output file for each build - otherwise how do you know which file you're using? Seems like an easy way to make a mistake.

Warning in the UI is a good idea. There are probably a handful of project.clj errors or warnings we should detect and inform the user.

**Comment by shaunlebron** [comment]
Closing.  Will track the warning bit in #96

**Comment by pgambling** [comment]
Yup, changed the file names and everything works now. Thanks!
