### ISSUE TITLE
Warn malformed project.clj

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cuttle#96]
We need to handle the following cases so the app does not freeze:

- [X] no cljsbuild config found
- [X] project.clj file not found
- [x] cannot parse project.clj at all
- [x] output files in builds must be unique (see #95)
- [x] output directories in builds must be unique (see #93)

I think after detecting a problem, a message should be shown in the build table explaining the problem.  This allows the user to hit refresh after fixing the problem.

**Comment by shaunlebron** [comment]
@oakmac can you add @comamitc as a contributor and assign him this issue?

**Comment by comamitc** [comment]
`project.clj file not found` doesn't seem to be a valid case if we are testing when you add a project to cuttle, close cuttle, remove the project.clj from the project tracked in cuttle. 

Cuttle currently removes this project from the workspace.

Is the case to safe guard deleting the project.clj file in the middle of auto builds?

**Comment by comamitc** [comment]
`cannot parse project.clj at all`: After examining this, cuttle should throw a generic application error. Mostly because if we cannot parse this file we cannot determine a lot of project details other than the file path.

**Comment by shaunlebron** [comment]
> `project.clj file not found` doesn't seem to be a valid case

good point, agreed.

> Is the case to safe guard deleting the project.clj file in the middle of auto builds?

Nah, auto-build works fine if its project.clj is deleted mid-build actually.

> `cannot parse project.clj at all`: After examining this, cuttle should throw a generic application error.

yeah good point, we couldn't even get the project name.  Thinking from the user perspective though, if Cuttle already knows about a project and the user makes a mistake modifying project.clj, maybe Cuttle should keep the cached name.

**Comment by comamitc** [comment]
96-4 is fixed already in function `cuttle.cljsbuild.config/set-default-output-dirs` but I'm making it not throw.

**Comment by comamitc** [comment]
closed with merge. Not sure why git didn't do it here.
